{% set version = "0.9.3" %}
{% set eccodes_version = "2.14" %}

package:
  name: python-eccodes
  version: {{ version }}

source:
  url: https://github.com/ecmwf/eccodes-python/archive/{{ version }}.tar.gz
  sha256: 45ec0383a831054a9e775c5fde706ddd21ad0a6177df8f6a8cbd5ab0f80fdf76

build:
  number: 1
  skip: True  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cffi  # [not win]
    - eccodes ={{ eccodes_version }}
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - cffi  # [not win]
    - attrs
    - eccodes ={{ eccodes_version }}

test:
  imports:
    - eccodes
    - gribapi
    - gribapi._bindings  # [not win]

about:
  home: https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: ECMWF ecCodes Copyright 2017-2019 ECMWF.
  dev_url: https://github.com/ecmwf/eccodes-python

extra:
  recipe-maintainers:
    - kmuehlbauer
    - pelson
    - ocefpaf
    - kynan
    - dtip
