{% set version = "2020.01.0" %}
{% set eccodes_version = "2.14" %}

package:
  name: python-eccodes
  version: {{ version }}

source:
  url: https://github.com/ecmwf/eccodes-python/archive/{{ version }}.tar.gz
  sha256: 069f2df4afe772e096f1e9b1919f87ad32bf014a60e4193b8a72f6c3fd79c056

build:
  number: 0
  skip: True  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cffi
    - eccodes ={{ eccodes_version }}
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - cffi
    - attrs
    - eccodes ={{ eccodes_version }}

test:
  imports:
    - eccodes
    - gribapi
    - gribapi._bindings  # [not win]

about:
  home: https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: ECMWF ecCodes Copyright 2017-2019 ECMWF.
  dev_url: https://github.com/ecmwf/eccodes-python

extra:
  recipe-maintainers:
    - kmuehlbauer
    - pelson
    - ocefpaf
    - kynan
    - dtip
