{% set version = "0.9.2" %}

package:
  name: python-eccodes
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/eccodes-python/eccodes-python-{{ version }}.tar.gz
  sha256: 587dd828ee5e13b6a7d35a362d6fd903d914dd0422f4010af95e8f45738e9143

build:
  number: 0
  skip: True  # [win or py2k]
  detect_binary_files_with_prefix: true

requirements:
  host:
    - python
    - pip
    - numpy
    - eccodes >=2.13.0
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - cffi
    - attrs
    - eccodes >=2.13.0

test:
  imports:
    - eccodes
    - gribapi

about:
  home: https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: ECMWF ecCodes Copyright 2005-2018 ECMWF.
  dev_url: https://github.com/ecmwf/eccodes-python

extra:
  recipe-maintainers:
    - kmuehlbauer
    - pelson
    - ocefpaf
    - kynan
