{% set version = "0.9.2" %}

package:
  name: python-eccodes
  version: {{ version }}

source:
  url: https://github.com/ecmwf/eccodes-python/archive/{{ version }}.tar.gz
  sha256: 1b228ad1589616b492a9377a68aa67ec42c1ecb681ae53d3d6ac83cb213c2c51

build:
  number: 0
  skip: True  # [win or py2k]

requirements:
  host:
    - python
    - pip
    - numpy
    - cffi
    - eccodes >=2.13.0
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - cffi
    - attrs
    - {{ pin_compatible('eccodes') }}

test:
  imports:
    - eccodes
    - gribapi

about:
  home: https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: ECMWF ecCodes Copyright 2017-2019 ECMWF.
  dev_url: https://github.com/ecmwf/eccodes-python

extra:
  recipe-maintainers:
    - kmuehlbauer
    - pelson
    - ocefpaf
    - kynan
