{% set version = "2.8.0" %}

package:
  name: python-eccodes
  version: {{ version }}

source:
  url: https://software.ecmwf.int/wiki/download/attachments/45757960/eccodes-{{ version }}-Source.tar.gz
  sha256: e0ba24c27cdd8133670fa3ea32be951d54030f2b880cacc9a9d87d9dbf372e1b

build:
  number: 2
  skip: True  # [win or py3k]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - perl
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - boost
    - jasper
    - libpng
    - libnetcdf
    - hdf5
    - eccodes {{ version }}
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - jasper
    - libpng
    - libnetcdf
    - hdf5
    - eccodes {{ version }}

test:
  imports:
    - eccodes
    - gribapi

about:
  home: https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
  license: Apache 2.0
  license_family: Apache
  summary: ECMWF ecCodes Copyright 2005-2018 ECMWF.

extra:
  recipe-maintainers:
    - kmuehlbauer
    - pelson
    - ocefpaf
    - kynan
