{% set version = "2.13.1" %}

package:
  name: python-eccodes
  version: {{ version }}

source:
  url: https://confluence.ecmwf.int/download/attachments/45757960/eccodes-{{ version }}-Source.tar.gz
  sha256: 158021539a85ca597075f4a534117721ea51f5ddea44b5ec27519d553c980f8d

build:
  number: 0
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - perl
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - boost
    - jasper
    - libpng
    - libnetcdf
    - hdf5
    - eccodes {{ version }}
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - jasper
    - libpng
    - libnetcdf
    - hdf5
    - eccodes {{ version }}

test:
  imports:
    - eccodes
    - gribapi

about:
  home: https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
  license: Apache 2.0
  license_family: Apache
  summary: ECMWF ecCodes Copyright 2005-2018 ECMWF.

extra:
  recipe-maintainers:
    - kmuehlbauer
    - pelson
    - ocefpaf
    - kynan
