{% set version = "0.9.3" %}
{% set eccodes_version = "2.13" %}

package:
  name: python-eccodes
  version: {{ version }}

source:
  url: https://github.com/ecmwf/eccodes-python/archive/{{ version }}.tar.gz
  sha256: 8203f7a4b340649cb27a1ac477d0b3ead195396502bd66467b57e944c6cf6ac8

build:
  number: 0
  skip: True  # [win or py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cffi
    - eccodes ={{ eccodes_version }}
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - cffi
    - attrs
    - eccodes ={{ eccodes_version }}

test:
  imports:
    - eccodes
    - gribapi
    - gribapi._bindings

about:
  home: https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: ECMWF ecCodes Copyright 2017-2019 ECMWF.
  dev_url: https://github.com/ecmwf/eccodes-python

extra:
  recipe-maintainers:
    - kmuehlbauer
    - pelson
    - ocefpaf
    - kynan
