{% set version = "2.0.0" %}

package:
  name: python-eccodes
  version: {{ version }}

source:
  url: https://software.ecmwf.int/wiki/download/attachments/45757960/eccodes-{{ version }}-Source.tar.gz
  fn: eccodes-{{ version }}-Source.tar.gz
  sha256: 338b311df338950ace79a8d26ffae17f3425bdc56cb8b36b620a69f5841b64f0

build:
  number: 0
  skip: True  # [win or py3k]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - python
    - numpy x.x
    - boost 1.61.*
    - jasper
    - libpng >=1.6.23,<1.7
    - libnetcdf 4.4.*
    - perl
    - eccodes {{ version }}
  run:
    - python
    - numpy x.x
    - boost 1.61.*
    - jasper
    - libpng >=1.6.23,<1.7
    - libnetcdf 4.4.*
    - perl
    - eccodes {{ version }}

test:
  imports:
    - eccodes
    - gribapi

about:
  home: https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
  license: Apache 2.0
  license_family: Apache
  summary: ECMWF ecCodes Copyright 2005-2016 ECMWF.

extra:
  recipe-maintainers:
    - kmuehlbauer
    - pelson
    - ocefpaf
    - kynan
