travis:
  secure:
    BINSTAR_TOKEN: ArwZyIIeyLhikB6P6COQp49m2or4Zb7wPNNVOdciliQd2RI7hYLDex1ZJRSFO7AdAm0p7A2W32BrDed59328RDjKX/wMZ9eCj4+xdmeHwvwIGPIdzUlkGiEWxHg8F5/DtJDxyy7XYg6ycjRP1DC7covVo8vQDm3+sLa7SNbRe5qOFXrw4HkJ2USiov6zY5s+bs+Ge/Qp4soRFgQBRHTXyb+krhGZOtGwppCdWF5lOipcG3bkuzHqNDDBXq4rL6XGSl8JtgU2TlJfnFn/2KruM2sNsUxxbLgR3GToAAQN84+LWpcuWL4g9gM7nTdbZC9U4TjRB/127D3pqe39UatPtkxlzECEkle8BuecNvCCwLdT03colbpgUj2Q+TrWtnNqh36y2OdPeuPnHpJ+KFkSw38/V4QLd/FfcaGFTWiE2L9xC326IzSyhc5Rp4juZ6pEeFezt9G13V6NOsCcR2kdd9aVzDdkTq22wazwAMX2rPr3sRF6TloI4XnmBsBhy5jPHU/9t14peGVVdLJs8kUdmpM14oNNnPJBrcKXu91jI0ijshPgHnGbbPXs6Zk18maSc0uIeMiOnXVoh/2qO+GMhsSzo6PEXUiIvB5EcPAC0sGI5qr0MiEZ2pbcLIJJtPArijQnR205GcRowAV6vfVVfEeR7Mt2on0juzqcdZwKsXc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
