travis:
  secure:
    BINSTAR_TOKEN: aLx/7SM8cpNzQE1kk0W3kUsLDY5T0iMF7NNfxm+xbB+OU8NtdnFMU+xCb3jn7NuwvioXqmwdy1KCSGZI/rQrPORpQoo8PKyOPSdLy5h6S++ocxRFkRYcijQJ+gGNdJ5N9kinGsUFw/2Cd6tBnhTSr6O5Qe+gRQawkR5FygYiq2WHYZnTMILRcvUsY6cvjyUp5XrKAkNJtxCFmBs9RA3mwHRsnw8ABWdkoe6UYkwsyAe7D+bt5OXN4PVQ0EKhJaRPSscS9NLyicDjOIOCfGgW9a4uuniOARVOQeVbEH3LUlgNdhnb1EYJTOZ/f5+74TQ3BRx7tm9HDCxOQEJXDYFi3cDG0lSZFEumxW9SgbaEngzFiGGSdKRAiTaq0lqqTwrtmc7YgSxzGx/1RIFRR5xnc7+DBo3r9TSjv5AIiHDMtd4l3q7ogZLqwsFtvm056lPKHzCk8HRuvKiUJqk4rj5OsK4dQ4VZuvy3hnFzMB5eyHSrOl1AbLWDr5IiMbI+n74zB9aE+WuHIe/BETFHumxCffcFCOdsof01YAwROHcJIKwe5Wo/4RLjiub8BS4LCqxEktj4qjHWr3kvuaT//QFfckDRfCi9/KhduC8KMNzaZo1uCJV86ENinz239h/14ftLU18LUtKsxSrsImpsCDb8Np59pc2uGH3o8yIZOPSk+7o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
